export type Memory = {
  id: string;
  authorName: string;
  authorMeta: string;
  authorBatch?: string;
  university: string;
  imageUri: string;
  avatarUri: string;
  tags: string[];
  dateLabel?: string;
  likesCount?: string;
  title?: string;
  reflection?: string;
  hasVoice?: boolean;
  voiceUrl?: string;
  voiceLabel?: string;
  voiceDuration?: string;
  likedByMe?: boolean;
  createdAt?: string;
};
